### ISSUE TITLE
EV3 firmware flash stuck on bootloader_start call and returned VM_SYS_RQ reply

### ISSUE THREAD

**Issue by ihormudryy** [c4ev3/ev3duder#32] opened 2021-01-19 09:34 UTC
I tried to flash my EV3 using ev3duder from the HEAD of master branch and bricked my device. All attempts to reflash it were failed.

After spending some time debugging I figured out that VM returned 0x01 reply in bootloader_start function call which is defined as VM_SYS_RQ internally.

Only changing FW request from FW_START_DOWNLOAD to FW_START_DOWNLOAD_WITH_ERASE helped and solved the issue in blinstall.c file in bootloader_start function. 
`FW_START_DOWNLOAD *request = packet_alloc(FW_START_DOWNLOAD, 0);`
`FW_START_DOWNLOAD_WITH_ERASE *request = packet_alloc(FW_START_DOWNLOAD_WITH_ERASE, 0);`

System info:
Linux kernel 5.8.0-38-generic 
Ubuntu 20.10 
SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by JakubVanek** [comment] 2021-01-19 11:14
Hi!

did you use a USB 3.0 or newer port to do the flashing? I faced similar issues, but I could reproduce the issue with all commands. Does `ev3 flash info` work for you? I cannot get it to work on my USB3-only laptop.
```
kuba@oggy-kuba:~$ ev3 flash info
USB connection established.

Error: ev3duder received its own packet instead of a reply from the brick.

If you have plugged the EV3 into a USB 3.0 port (usually red or blue),
try plugging it into a USB 2.0 only port (usually black or white).
```

I used the `FW_ERASEFLASH` + `FW_START_DOWNLOAD` combination as this is what https://github.com/ev3dev/lms-hacker-tools/blob/248402493510b7f072f945ad87021643ca9f2721/PBrickTools/Ev3FirmwareLoader.Cli/Program.cs#L102 uses. I'm not currently sure what the stock EV3 application for Windows sends, it could be using either of those options (either it waits for reply on `FW_START_DOWNLOAD_WITH_ERASE`, or on `FW_ERASEFLASH`).

With that being said, if `FW_START_DOWNLOAD_WITH_ERASE` works just as well, there should be no problem with using that.

However, I'm not sure that this is really going to prevent bricking the brick. If the flash is erased before brick sends the first reply and the download then fails in the middle with E_USBLOOP, the firmware won't boot either. However, if it did work for you, it's indeed possible that on some PCs, `FW_START_DOWNLOAD_WITH_ERASE` avoids this problem.

Adding something like "do not try this with USB 3.0, press Ctrl+C to cancel this (timeout 10s)" might be a better alternative.

Alternatively, the VM_SYS_RQ replies could be regarded as OK replies with the caveat that the checksum cannot be checked (no way to extract the information).

I am happy to test this, but in the coming weeks I may not have much time for this.

With regards,

Jakub

**Comment by JakubVanek** [comment] 2021-01-19 11:20
My HW/SW:
* Laptop: Fujitsu Lifebook E734
* USB controller (from lspci): 00:14.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI [8086:8c31] (rev 04) (prog-if 30 [XHCI])
* Kernel: Linux oggy-kuba 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Distro: Ubuntu 18.04.5 LTS

**Comment by ihormudryy** [comment] 2021-01-19 11:44
Hi Jakub,

Thanks for the prompt and constructive reply! I have USB 3.0 on my DELL Precision 5530 laptop
```
lspci | grep USB
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
```

> Alternatively, the VM_SYS_RQ replies could be regarded as OK replies with the caveat that the checksum cannot be checked (no way to extract the information).

I tried to comment this section out where it calls return if a reply is VM_SYS_RQ, as I also thought that it could proceed with flashing, but it gets into the error state anyway on the next bootloader_send call.

> Does `ev3 flash info` work for you?

Nope, it doesn't. Having working latest firmware v1.10E installed by ev3duder I get an error in update mode:
`
No updateable EV3 found. Plug it into a USB port and switch it to firmware update mode.
`

> However, I'm not sure that this is really going to prevent bricking the brick. If the flash is erased before brick sends the first reply and the download then fails in the middle with E_USBLOOP, the firmware won't boot either. However, if it did work for you, it's indeed possible that on some PCs, `FW_START_DOWNLOAD_WITH_ERASE` avoids this problem.

Sincerely, I was very frustrated when the brick was bricked and almost wanted to buy a new one. My C/C++ skills are limited and I had to read some things to refresh my knowledge, but ultimately I've found a way to overcome this annoying issue. So having said that I mean that just erasing the flash and exiting with error could be very shocking for someone as it looks like an internal EV3 error which is not possible to fix afterward. 

BTW. Windows 10 and 7 in Virtualbox doesn't recognize my device (unknown USB device) after flashing though I tried to use officially signed drivers. I haven't tried to do it before I flashed the device, but it would be interesting.

Kind regards
Ihor

**Comment by ihormudryy** [comment] 2021-01-19 11:48
Sorry, the correct reply from `ev3duder flash info` is as the previous one I ran not as sudo.
```
USB connection established.

Error: ev3duder received its own packet instead of a reply from the brick.
```

**Comment by JakubVanek** [comment] 2021-01-19 18:12
> Sincerely, I was very frustrated when the brick was bricked and almost wanted to buy a new one. My C/C++ skills are limited and I had to read some things to refresh my knowledge, but ultimately I've found a way to overcome this annoying issue. So having said that I mean that just erasing the flash and exiting with error could be very shocking for someone as it looks like an internal EV3 error which is not possible to fix afterward.

I agree and I'm sorry, this is my fault and bricking the brick (with only "safe" recovery option being using USB 2.0, which may not be available anymore) is a really bad user experience.

> BTW. Windows 10 and 7 in Virtualbox doesn't recognize my device (unknown USB device) after flashing though I tried to use officially signed drivers. I haven't tried to do it before I flashed the device, but it would be interesting.

Could you try shutting the brick down and then starting it again? This might be related to a change in how the device presents itself to the OS - first, it's a firmware upgrade device, then it changes into the standard EV3 device.

The fact that `ev3duder flash info` doesn't work and that the flashing with https://github.com/c4ev3/ev3duder/pull/33 succeeds is interesting. I will try to investigate this some more. I'm also starting to think that requiring USB 2.0 isn't viable in the long run, as these ports will get more and more scarce (at least on laptops).

**Comment by JakubVanek** [comment] 2021-01-19 18:37
I can partially confirm the fix in https://github.com/c4ev3/ev3duder/pull/33:
```
kuba@oggy-kuba:~/lego/ev3/stock/ev3duder$ ./ev3duder flash install /home/kuba/lego/ev3/stock/firmwares/EV3-1.10E.bin 
USB connection established.
Erasing and Downloading...
Progress:   0 %
Progress:   5 %
Progress:  10 %
Progress:  15 %
Progress:  20 %
Progress:  25 %
Progress:  30 %
Progress:  35 %
Progress:  40 %
Progress:  45 %
Progress:  50 %
Progress:  55 %
Progress:  60 %
Progress:  65 %
Progress:  70 %
Progress:  75 %
Progress:  80 %
Progress:  85 %
Progress:  90 %
Progress:  95 %

Error: ev3duder received its own packet instead of a reply from the brick.

If you have plugged the EV3 into a USB 3.0 port (usually red or blue),
try plugging it into a USB 2.0 only port (usually black or white).
kuba@oggy-kuba:~/lego/ev3/stock/ev3duder$ ./ev3duder flash exit
USB connection established.
`FW_STARTAPP` was successful.
```

Afterwards, the brick successfully boots into the LEGO OS.

This likely means that when the brick is connected over USB 3.0, there is a problem with packets that take only a short time to process. `ev3duder flash info` is an example of this. A similar problem likely happens with the `FW_START_DOWNLOAD` command - the comment tells that it takes "extremely short time" to complete. This is why the upload always stopped after the flash got erased. I'd also guess that the end of the download loop is similar in this - something likely finishes finishes quicker there.

**Comment by JakubVanek** [comment] 2021-01-19 19:13
Here's a Wireshark USB capture with https://github.com/c4ev3/ev3duder/pull/33 applied: [fwupdate-fused.pcapng.gz](https://github.com/c4ev3/ev3duder/files/5838091/fwupdate-fused.pcapng.gz). I'll try if I can get the same capture from Windows.

**Comment by JakubVanek** [comment] 2021-01-19 19:34
I think the mystery has been solved. Old EV3 software running on Windows in a VMware virtual machine running on the same Linux OS managed to upgrade the brick successfully, even using the 0xF3 `FW_ERASEFLASH` command. This is a capture from the underlying Linux OS: [fwupdate-windows.pcapng.gz](https://github.com/c4ev3/ev3duder/files/5838186/fwupdate-windows.pcapng.gz)

It seems that the difference is that LEGO software simply takes the verbatim replies as valid replies. Packet 217 is the `FW_START_DOWNLOAD` command, reply to which is the same data in packet 219 (so it's not really a reply from the brick).

**Comment by JakubVanek** [comment] 2021-01-19 19:55
I have created https://github.com/c4ev3/ev3duder/pull/34 with an alternative fix - this simply accepts the packets that were rejected.

**Comment by ihormudryy** [comment] 2021-01-19 20:20
I verified and your fix works perfectly for flash install!

Yes, my commit was like a dirty hack and your is a proper way to fix it! Should I abandon my pull request or your will do it?

Thank you for your time and great support! I didn't know that I will go so deep when I was buying EV3 for my son as a Christmas gift :)

**Comment by ihormudryy** [comment] 2021-01-19 21:29
One more thing I wanted to ask you maybe not in GitLab, but privately. 

After flashing EV3 with all possible firmware versions starting from 1.05E I couldn't manage to make [MindCub3r](https://www.mindcuber.com/mindcub3r/mindcub3r.html) working anymore on my device. When the program starts it shows only a black stripe on top of the screen and no errors or whatsoever.

I don't know if some metadata is missing or maybe you could give me some hint? Or how can I get logs from the device?

**Comment by JakubVanek** [comment] 2021-01-19 21:29
Thank you! I also managed to reproduce the issue with disappearing USB device after the flashing procedure finishes. I added another commit to https://github.com/c4ev3/ev3duder/pull/34 to warn about this. I'm not sure I can fix this differently - plugging the brick into a different computer shows the same behaviour - the brick is not detected. Manually rebooting the brick from menu seems to help, however.

Closing the https://github.com/c4ev3/ev3duder/pull/33 is likely enough. I don't have write permissions here, so I cannot handle this on my own.

**Comment by JakubVanek** [comment] 2021-01-19 22:09
> When the program starts it shows only a black stripe on top of the screen and no errors or whatsoever.

This sounds like only a text file is getting opened. However, by using the SD card instructions together with ev3duder upload functionality, I managed to get something working:

1. download MindCub3r-v2p2-SD.zip from https://www.mindcuber.com/mindcub3r/mindcub3r-sd.html
2. extract it somewhere
3. run these commands to upload the program to the brick
```
ev3duder mkdir                                 /home/root/lms2012/prjs/MindCub3r
ev3duder up MindCub3r-v2p2/Error\ alarm.rsf    /home/root/lms2012/prjs/MindCub3r/Error\ alarm.rsf
ev3duder up MindCub3r-v2p2/InstallMC3-v2p2.rbf /home/root/lms2012/prjs/MindCub3r/InstallMC3-v2p2.rbf
ev3duder up MindCub3r-v2p2/mc3solver-v2p2.rtf  /home/root/lms2012/prjs/MindCub3r/mc3solver-v2p2.rtf
ev3duder up MindCub3r-v2p2/MindCub3r.rbf       /home/root/lms2012/prjs/MindCub3r/MindCub3r.rbf
ev3duder up MindCub3r-v2p2/mc3cmd.rtf          /home/root/lms2012/prjs/MindCub3r/mc3cmd.rtf
```
4. run Files (second tab) -> MindCub3r -> InstallMC3-v2p2 on the brick
5. (may not be necessary) run Apps (third tab) -> MC3 Solver v2p2
6. run Files -> MindCub3r -> MindCub3r

This launches some kind of an UI that might start working when something is done.

The following brick shutdowns might take a bit longer, as the uploaded files now have to be compressed and stored to brick memory.

**Closed** 2021-01-19 23:36 UTC

**Comment by ihormudryy** [comment] 2021-01-20 09:48
Ahh I used a wrong archive from their instructions page https://www.mindcuber.com/mindcub3r/MindCub3r-v2p2.zip
Sorry, my bad! With the correct one it worked for me too. Now the only thing I don't know is how to configure/calibrate color sensor sensitivity to properly recognize cubes colors as it shows wrong values and can not scan the cube properly. It's hard to understand what to do as the source code is not disclosed for this project.

**Comment by JakubVanek** [comment] 2021-01-20 14:21
It should be possible to open the `.ev3` (main program) and `.ev3b` (RGB color sensor blocks) using the old EV3 Software on Windows (not LEGO Classroom or some modern app). The `.rbf` file from the SD card archive is the compiled version of the program. The brick can only open `.rbf`, not `.ev3` files and the EV3 editor can only open `.ev3 files.

I managed to open the `.ev3` file and it seems that there's some code that could be adjusted. I haven't explored it much more, however. It also seems that there's some calibration code that might need to be activated.

**Comment by ihormudryy** [comment] 2021-01-20 16:13
Jakub, thanks a lot! I will be digging into this direction, just unfortunately Win 7/10 on VirtualBox doesn't recognize ev3 as a credible device in normal and FW update mode...

**Comment by laurensvalk** [comment] 2024-10-31 19:10
Message from the future :robot: , thanks for the notes in this issue! :smile: 

Small finding: even though `FW_GETVERSION` fails in the way described above, you can still get the hardware version from the reply. It seems that the brick does not technically send the host message back, but sends back its reply with the host message written over it. Since the host message is shorter than the reply in this case, we can still get the version info.
